compute_groups:
  group1:
    priority: 1
    region: centralus
    colour: 0722ef
    storage_colour: 0722ef
    nodes:
      compute_small:
        limit: 10
        priority: 1
      compute_other:
        limit: 10
        priority: 2
  group2:
    priority: 2
    region: uksouth
    colour: ef2d07
    storage_colour: ef2d07
    nodes:
      compute_small:
        limit: 2
        priority: 1
  group3:
    priority: 3
    region: westeurope
    colour: ef07bd
    storage_colour: ef07bd
